"""is_public en exercise

Revision ID: 0678362208c0
Revises: 66e41a784f34
Create Date: 2026-04-25 09:57:53.498118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0678362208c0'
down_revision: Union[str, Sequence[str], None] = '66e41a784f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_is_public'), 'exercise', ['is_public'], unique=False)
    op.alter_column('user', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_exercise_is_public'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_column('exercise', 'is_public')
    # ### end Alembic commands ###
