"""añadir goal a user

Revision ID: 554d0b8660fb
Revises: 594a07b7d0f7
Create Date: 2026-04-24 15:44:29.146514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554d0b8660fb'
down_revision: Union[str, Sequence[str], None] = '594a07b7d0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal', sa.String(length=50), nullable=False))
    op.alter_column('user', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_column('user', 'weight_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight_goal', sa.REAL(), autoincrement=False, nullable=False))
    op.alter_column('user', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('user', 'goal')
    # ### end Alembic commands ###
