"""añadir weight a user

Revision ID: 594a07b7d0f7
Revises: 6b5362643456
Create Date: 2026-04-24 15:37:14.683143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594a07b7d0f7'
down_revision: Union[str, Sequence[str], None] = '6b5362643456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.Float(precision=2), nullable=False))
    op.add_column('user', sa.Column('weight_goal', sa.Float(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight_goal')
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###
